Update golang-cicd

diff --git a/golang/1.12.4-alpine3.9/Dockerfile b/golang/1.12.4-alpine3.9/Dockerfile
--- a/golang/1.12.4-alpine3.9/Dockerfile
+++ b/golang/1.12.4-alpine3.9/Dockerfile
@@ -18,7 +18,51 @@ RUN apk add --no-cache python3 && \
 RUN pip3 install awscli --upgrade
 RUN apk add --no-cache openssh
 
+################# Setup docker
+
+ENV DOCKER_CHANNEL stable
+ENV DOCKER_VERSION 18.09.6
+# TODO ENV DOCKER_SHA256
+# https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
+# (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
+
+RUN set -eux; \
+	\
+# this "case" statement is generated via "update.sh"
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64) dockerArch='x86_64' ;; \
+		armhf) dockerArch='armel' ;; \
+		aarch64) dockerArch='aarch64' ;; \
+		ppc64le) dockerArch='ppc64le' ;; \
+		s390x) dockerArch='s390x' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	\
+	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+		exit 1; \
+	fi; \
+	\
+	tar --extract \
+		--file docker.tgz \
+		--strip-components 1 \
+		--directory /usr/local/bin/ \
+	; \
+	rm docker.tgz; \
+	\
+	dockerd --version; \
+	docker --version
+
+COPY modprobe.sh /usr/local/bin/modprobe
+COPY docker-entrypoint.sh /usr/local/bin/
+
+
+#################
+
+
 RUN apk -v --purge del py-pip && \
     rm /var/cache/apk/*
 
+ENTRYPOINT ["docker-entrypoint.sh"]
 CMD ["go"]
